config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "calories#index"
  get 'calories' => "calories#new"
  get 'users/:id' => "users#metabolism"
  get 'users' => "users#registrations"
  get 'targets' => "targets#new"
  resources :calories, only: [:new,:create] do
    collection do
      get 'tesma_about'
    end
  end
  resources :users, only: [:update] do
    collection do
      get 'metabolism'
    end
  end
  resources :targets, only: [:new,:create,:update] do
    collection do
      get 'target_index'
    end
  end
end

app/views/shared/_basal_about.html.erb
<div id="basal-logo-box">
<%=image_tag 'basal_logo.png', class: "basal-logo-image"%>
</div>

app/views/shared/_datepicker.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<!--Moment.jsの日本語ローカライズ用の言語ファイルを追加 -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>

app/views/shared/_down_logic.html.erb
<div id="logic-content">
    <div>
    <h2 class="last-logic-str">体脂肪を落とす計算式</h2>
    <div class="main-logic-str">
      (<div class="basal-inline">
      <p class="basal-inline" id="basal">
      基礎代謝量
      </p>
      <p id="basal-none">
      基礎代謝量とは、何もしなくても体温の維持や呼吸で必要最低限消費されるカロリーのこと。
      </p>
      </div> ✖️ 
      <div class="basal-inline">
      <p class="basal-inline" id="life-num">
      生活強度指数
      </p>
      <p id="life-num-none">
      生活強度指数とは、1日の生活のなかでどのくらいの負荷がかかっているかの数値です。基礎代謝量にかけることで消費カロリーが出せます。この数値は詳細を目標設定の画面で確認できます。
      </p>
      </div>） ー　食事による摂取カロリー　＝　（ここの数字が１以上になれば体脂肪が減り、痩せていきます）
    </div>
    
    <div class="media-414">
      (<div class="basal-inline">
      <p class="basal-inline" id="basal-media">
      基礎代謝量
      </p>
      <p id="basal-none-media">
      基礎代謝量とは、何もしなくても体温の維持や呼吸で必要最低限消費されるカロリーのこと。
      </p>
      </div> ✖️ 
      <div class="basal-inline">
      <p class="basal-inline" id="life-num-media">生活強度指数
      </p>
      <p id="life-num-none-media">
      生活強度指数とは、1日の生活のなかでどのくらいの負荷がかかっているかの数値です。基礎代謝量にかけることで消費カロリーが出せます。この数値は詳細を目標設定の画面で確認できます。
      </p>
      </div>) ー 食事による摂取カロリー
      <p>= （ここの数字が１以上になら体脂肪が減ります）</p>
    </div>

    </div>
     <%=image_tag 'keisansiki_image.png', class: "main-logic-image"%>
  </div>

 

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer-content">
  <div class="footer-logo">
    <%= link_to image_tag("tesma_logo_footer.jpeg", class: "tesma_logo_icon footer-icon"),"/"%>
  </div>
</div>

app/views/shared/_header.html.erb
<div id="header-content">
  <div class="header-box">
  <div class="header-logo">
    <%= link_to image_tag("tesma_logo.jpeg", class: "tesma_logo_icon"),"/"%>
  </div>
  <div class="user-relation">
      <ul class="session-user">
      <% if user_signed_in?%>
        <li><%=link_to current_user.name, "#"%></li>
        <li><%=link_to "ログアウト",  destroy_user_session_path ,method: :delete%></li>
        <% else%>
        <li><%=link_to "ログイン", new_user_session_path %></li>
        <li><%=link_to "新規登録", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <div class="header-row">
    <div class="select-block">
      <ul class="select-list">
        <%= link_to  new_calory_path do%>
        <li id="h_kcal">カロリー計算</li>
        <%end%>
        <%= link_to  metabolism_users_path do%>
        <li id="h_metabo">基礎代謝管理</li>
        <%end%>
        <%= link_to  new_target_path do%>
        <li id="h_target">目標設定</li>
        <%end%>
        <%= link_to  target_index_targets_path do%>
        <li id="h_index">目標進捗</li>
        <%end%>
        <%= link_to tesma_about_calories_path do%>
        <li id="h_about">TESMAについて</li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_header_short.html.erb
<div class="header-short">
<div class="header-logo">
    <%= link_to image_tag("tesma_logo.jpeg", class: "tesma_logo_icon"),"/"%>
  </div>
  </div>

app/views/shared/_hidden_add.html.erb
<div class="hidden-field wrap-hidden1">
  <li id="hidden1">ooo</li>
    <input  class= "menu-name">g
   </div>
<div class="hidden-field wrap-hidden2">
 <li id="hidden2">ooo</li>
   <input class= "menu-name">g
</div>
<div class="hidden-field wrap-hidden3">
   <li id="hidden3">ooo</li>
   <input class= "menu-name">g
</div>

app/views/shared/_logo_short.html.erb
<div class="header-short">
<div class="header-logo">
    <%= link_to image_tag("tesma_logo.jpeg", class: "tesma_logo_icon"),"/"%>
  </div>
  </div>

app/views/shared/_tesma_introduction.erb
<div id="tesma-concept" data-display="<%=@data%>">
    <h2>TESMAとは</h2>
    <p class="tesma-concept-p">The essential self management(本質的な自身の管理)の略称です。
    </p>
    <p class="tesma-concept-p">
      現代では、様々なダイエット法や食事制限での減量などの情報で溢れていますが、
    </p>
    <p class="tesma-concept-p">
    例えば食事制限を行うようなダイエットでは、
    </p>
    <ul class="personnel-lists">
    <li>「リバウンドしやすい」</li>
    <li>「長続きしない」</li>
    <li>「体重は減ったけど十分な栄養を摂取できていない」</li>
    </ul>
    <p class="tesma-concept-p">
    などの声が非常に多いように感じます。
    </p>
     <p class="tesma-concept-p">
     理想は、体重計に乗った時の数字が瞬間的に減ったかどうかではなく、
     <br>
     <span>長期的に継続することができ、理想の体型を維持することがダイエットの本質ではないでしょうか。</span>
     <p class="tesma-concept-p">
      そこで本アプリでは、設定された目標体重から1日の摂取カロリーを算出し、基礎代謝の維持や向上をしてもらうことで、計画的に理想に近づくことができます。
      </p>
      <p class="tesma-concept-p">
      過度な食事制限はせず、リバウンドのしにくい理想の体を手に入れましょう。
      </p>
</div>